name: Deploy to FTP

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.185.162.93.61 }}
          username: ${{ secrets.skrebeiko_meetings }}
          password: ${{ secrets.tW7nA8qK8l }}
          port: ${{ secrets.21 }}
          local-dir: build/
          server-dir: /www/meetings.skrebeyko.ru/
          dangerous-clean-slate: true
